[package]
name = "ferrous-irc"
version = "0.2.0"
authors = [ "Jack Champagne" ]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.x", features = ["full"] }

[profile.release]
debug = false
